### ISSUE TITLE
library "libwind.so" not found

### ISSUE THREAD

**Issue by notsb** [rxreader/weibo_kit#23]
我用x86模拟器时出现这个错误，好像是没有对应的so文件。
Syncing files to device sdk gphone x86...
E/flutter (10691): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: dlopen failed: library "libwind.so" not found

**Comment by CoderLengary** [comment]
Android 真机运行就可以了
