### ISSUE TITLE
Android 微博分享-微博没有登录状态下：返回app出现一个loading界面，能够返回关闭。

### ISSUE THREAD

**Issue by Witcher-jufei** [rxreader/weibo_kit#25]
![WechatIMG9](https://user-images.githubusercontent.com/55491257/104327845-2e5e9200-5526-11eb-9ecf-03267dfb5703.jpeg)
用的Demo里的代码

**Comment by BoyYangyang** [comment]
同样的问题,请问怎么处理的

**Comment by Witcher-jufei** [comment]
已经修复，没有了。
