### ISSUE TITLE
Could not resolve com.sina.weibo.sdk:core:9.12.0.

### ISSUE THREAD

**Issue by hchen1987** [rxreader/weibo_kit#36]
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.sina.weibo.sdk:core:9.12.0.
     Required by:
         project :app > project :weibo_kit
      > Could not resolve com.sina.weibo.sdk:core:9.12.0.
         > Could not get resource 'https://google.bintray.com/exoplayer/com/sina/weibo/sdk/core/9.12.0/core-9.12.0.pom'.
            > Could not GET 'https://google.bintray.com/exoplayer/com/sina/weibo/sdk/core/9.12.0/core-9.12.0.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.sina.weibo.sdk:core:9.12.0.
         > Could not get resource 'https://dl.bintray.com/umsdk/release/com/sina/weibo/sdk/core/9.12.0/core-9.12.0.pom'.
            > Could not GET 'https://dl.bintray.com/umsdk/release/com/sina/weibo/sdk/core/9.12.0/core-9.12.0.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.sina.weibo.sdk:core:9.12.0.
         > Could not get resource 'https://dl.bintray.com/thelasterstar/maven/com/sina/weibo/sdk/core/9.12.0/core-9.12.0.pom'.
            > Could not GET 'https://dl.bintray.com/thelasterstar/maven/com/sina/weibo/sdk/core/9.12.0/core-9.12.0.pom'. Received status code 403 from server: Forbidden

**Comment by v7lin** [comment]
请用 git 方式引入最新代码
