### ISSUE TITLE
com.sina.weibo.sdk:core:9.12.0.

### ISSUE THREAD

**Issue by xiaoshengyuyu** [RxReader/weibo_kit#45]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.sina.weibo.sdk:core:9.12.0.
     Required by:
         project :app > project :weibo_kit
      > Could not resolve com.sina.weibo.sdk:core:9.12.0.
         > Could not get resource 'https://google.bintray.com/exoplayer/com/sina/weibo/sdk/core/9.12.0/core-9.12.0.pom'.
            > Could not GET 'https://google.bintray.com/exoplayer/com/sina/weibo/sdk/core/9.12.0/core-9.12.0.pom'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
Exception: Gradle task assembleDebug failed with exit code 1

项目用的flutter 版本是 1.20.0    需要怎么修改

**Comment by v7lin** [comment]
jcenter 早跪了 … 最简单方式fork一份工程，改成非nullsafe
