### ISSUE TITLE
ios set app  Associated Domains  has error

### ISSUE THREAD

**Issue by zmtzawqlp** [RxReader/weibo_kit#46]
lanuch app with  UniversalLinks，it will go into this method and got error.
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * _Nonnull))restorationHandler {
    return [WeiboSDK handleOpenUniversalLink:userActivity delegate:self];;
}

**Comment by v7lin** [comment]
@zmtzawqlp 看一下 Weibo_SDK 的版本号

**Comment by zmtzawqlp** [comment]
> @zmtzawqlp 看一下 Weibo_SDK 的版本号

3.3.0

**Comment by droplet-js** [comment]
我最近刚写的，[Flutter版深度链接](https://github.com/RxReader/link_kit)
