### ISSUE TITLE
应用审核不通过，反馈“您的应用在用户同意隐私政策前申请获取用户的 ANDROID ID个人信息”。

### ISSUE THREAD

**Issue by quinoxz** [RxReader/weibo_kit#47]
应用审核不通过，反馈“您的应用在用户同意隐私政策前申请获取用户的 ANDROID ID个人信息”。
尊敬的开发者，您好，您的应用在用户同意隐私政策前申请获取用户的【ANDROID ID】个人信息，请参考以下调用栈，可协助您定位问题，并将相关信息获取调整至同意政策之后，谢谢。

[com.weibo.ssosdk.MfpBuilder.getAndroidId(SourceFile:1),

 com.weibo.ssosdk.MfpBuilder.genMfpString(SourceFile:32),

 com.weibo.ssosdk.MfpBuilder.getMfp(SourceFile:1),

 com.weibo.ssosdk.WeiboSsoSdk.updateInfo(SourceFile:8),

 com.weibo.ssosdk.WeiboSsoSdk.access$200(SourceFile:1),

 com.weibo.ssosdk.WeiboSsoSdk$e.run(SourceFile:1),

 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167),

 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641),

 java.lang.Thread.run(Thread.java:933)]

**Comment by chiluo** [comment]
遇到同样问题，请问是如何解决的
