### ISSUE TITLE
微博的AuthResp类中expiresIn这个字段别用int类型接收，安卓手机这个使用int,接收的数值为负数，应该使用长整形或者字符串类型，都比这个好。我们遇到过这个bug。希望能尽快修改谢谢。

### ISSUE THREAD

**Issue by 15949893621** [RxReader/weibo_kit#48]

**Comment by v7lin** [comment]
?
Flutter上的 int32（int）和 int64（long）都是 int 表示，插件里 java 部分 expiresIn 为 long 型，oc 部分为 long long 型，不明白你的 BUG 是啥？

**Comment by 15949893621** [comment]
您好，好高兴收到您的回复。
我给您接了一张图片。我使用的是华为手机，鸿蒙2.0.0系统。
监听到微博回调给的数据，expiresIn这个成负数了。
我们以前做安卓原生开发的时候也越到过这种问题，就是因为当时我们使用int类型去解析的这个字段，后来我们该成Long类型就可以了。


变成负数和他们给的原始数值是不一样的。


谢谢！











在 2022-07-22 14:31:00，"沉默的湮灰" ***@***.***> 写道：

?
Flutter上的 int32（int）和 int64（long）都是 int 表示，插件里 java 部分 expiresIn 为 long 型，oc 部分为 long long 型，不明白你的 BUG 是啥？

**Comment by 15949893621** [comment]
您好，好高兴收到您的回复。
我给您接了一张图片。我使用的是华为手机，鸿蒙2.0.0系统。
监听到微博回调给的数据，expiresIn这个成负数了。
![截屏2022-07-22 21 22 08](https://user-images.githubusercontent.com/17999816/180449216-b18c80ff-56c2-4288-815d-5de197a1e7a6.png)
[](url)
我们以前做安卓原生开发的时候也越到过这种问题，就是因为当时我们使用int类型去解析的这个字段，后来我们该成Long类型就可以了。

变成负数和他们给的原始数值是不一样的。

谢谢！
